language: java
jdk: oraclejdk8
install: true
cache:
  directories:
  - $HOME/.m2
env:
  global:
    - LD_LIBRARY_PATH = TRAVIS_BUILD_DIR
script:
  - mvn clean install -Djava.library.path=TRAVIS_BUILD_DIR
  - mvn cobertura:cobertura
  - mvn checkstyle:check
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
