language: java
jdk: oraclejdk8
install: true
before_install:
  - export LD_LIBRARY_PATH=$HOME/libs/:$LD_LIBRARY_PATH
cache:
  directories:
  - $HOME/.m2
script:
  - mvn clean install
  - mvn cobertura:cobertura
  - mvn checkstyle:check
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
