package ui;

import core.model.inventory.impl.storage.DoubleStorage;
import core.model.network.impl.DoubleNetwork;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author VALERY-PC
 */
public class UserForm extends javax.swing.JFrame {
    // Frame
    private static JFrame frame;
    
    // Panels
    private static NetworkPanel networkPanel;
    private static GeneticPanel geneticPanel;

    // Entities
    private DoubleStorage storage;
    private DoubleNetwork network;
    
    
    /**
     * Creates new form USerForm
     */
    public UserForm() {
        initComponents();
        storage = new DoubleStorage();
        network = new DoubleNetwork();
        UserForm.networkPanel = new NetworkPanel(storage, network);
        this.geneticPanel = new GeneticPanel(storage, network);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        nextPreviousButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Network Analyzer");
        setBackground(java.awt.SystemColor.window);
        setPreferredSize(new java.awt.Dimension(960, 730));
        setResizable(false);

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        nextPreviousButton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        nextPreviousButton.setText("Next");
        nextPreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPreviousButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addContainerGap(875, Short.MAX_VALUE)
                                .addComponent(nextPreviousButton)
                                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
                jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nextPreviousButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(696, Short.MAX_VALUE)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextPreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPreviousButtonActionPerformed
        if (nextPreviousButton.getText().equals("Next")) {
            frame.remove(networkPanel);
            frame.add(geneticPanel, BorderLayout.PAGE_START);
            frame.repaint();
            nextPreviousButton.setText("Previous");
        } else {
            frame.remove(geneticPanel);
            frame.add(networkPanel, BorderLayout.PAGE_START);
            frame.repaint();
            nextPreviousButton.setText("Next");
        }
    }//GEN-LAST:event_nextPreviousButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame = new UserForm();
                frame.setLayout(new BorderLayout());
                frame.setVisible(true);
                frame.add(networkPanel, BorderLayout.PAGE_START);
                frame.getContentPane().setBackground(Color.white);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel13;
    private javax.swing.JButton nextPreviousButton;
    // End of variables declaration//GEN-END:variables
}
